### PR TITLE
update to latest ta4j version 0.18-SNAPSHOT

### PR DESCRIPTION
**Pull request by Andre0711er**
- update to latest version of ta4j (0.18-SNAPSHOT)
- update to latest java LTS version 21

### CODE REVIEW

**Comment by Cypher01** [comment]
Thx for the PR, but I see multiple problems.

* ~~ta4j-core is based on Java 11. This shouldn't be changed for compatibility.~~ &rarr; _Just realized v0.18-SNAPSHOT is actually based on Java 21._
* I prefer to use a release version of ta4j-core as basis. When using a snapshot, every new build could cause incompatibilities. I know, there are no real releases of ta4j-extended yet, I need to find a strategy.
* I put great store on code quality. And you changed the indents on many lines from tabs to spaces for no reason.

I will update to ta4j-core v0.17, but I cannot merge this PR as is.

**Comment by nimo23** [comment]
@Cypher01 I came to this project via https://github.com/ta4j/ta4j/issues/1126#issuecomment-1862314271.

Would you mind contributing your indicators/rules/criteria to ta4j project? 
This doesn't mean that all classes will be merged, but we can then look together at which ones make sense to merge into the main project.
This also gives this codebase the chance to be reviewed by multiple people and at least possibly maintained and/or improved in the long term.

**Comment by Cypher01** [comment]
@nimo23 I would be glad to contribute to the ta4j project!

How could we organize that? To be honest, the reason why I created my own extension is, that I was just lazy to create pull requests. And `ta4j-extended` already consists of over 40 indicators (including helpers), and I have even more in the pipeline (partly unfinished, partly done but untested). I'm not too motivated to create so many PRs right away.

I suggest, that we put together a list of let's say 10 to 20 indicators/rules/criteria, which I will create PRs for. When these are reviewed, we will check how we continue from that. According to the other thread, `KRIIndicator` seems to be a good first candidate.

What do you think?

**Comment by nimo23** [comment]
@Cypher01 That sounds great. Thanks! Just do the PR's and we'll see.

**Comment by Andre0711er** [comment]
@Cypher01 Might be great, to contribute back to ta4j. There's no existing unit tests yet. I can help here and will write some.
I'm in vacation right now, will review my PR and will try to clean up.

**Comment by Cypher01** [comment]
@Andre0711er I gladly accept the offer to write tests.
In short, I tested the indicators by visual inspection. I use [this tool](https://github.com/team172011/ta4jCharting) to preview the indicator and align the window on the screen with the source where I found the indicator (mostly TradingView). A few quick Alt-Tab's, focusing primarily on pivot points, reveals if the implemention is correct. Weird, I know, but it works.

**Pull request closed without merging**
